### ISSUE TITLE
FRQ: chemfiles reader.

### ISSUE THREAD

**Issue by hechtprojects** [amepproject/amep#13]
### Proposed new feature or change:

To enable the loading of various simulation data formats, AMEP should provide a new reader class based on the Chemfiles Python library (https://chemfiles.org/). This new reader class should be implemented as `ChemfilesReader` in the module `amep.reader`. It should convert the loaded data to the `.h5amep` format.

**Comment by hechtprojects** [comment]
Focus on a reader for GROMACS data first.

**Comment by kay-ro** [comment]
chemfiles is very slow at reading long trajectories.
An alternative might be the combination of
- `TprParser` https://pypi.org/project/TprParser/ and
- `pytrr` https://pypi.org/project/pytrr/

And check methods of 
- [ ] `MDAnalysis` https://www.mdanalysis.org/ or 
- [ ] `MDTraj` https://www.mdtraj.org/

**Comment by kay-ro** [comment]
general chemfiles reader not yet planned. For now only using it for Gromacs.
Further implementations are straight forward.
