### ISSUE TITLE
FRQ: Support for gsd files. Format of hoomd-blue

### ISSUE THREAD

**Issue by kai-luca** [amepproject/amep#37]
### Proposed new feature or change:

Since I'm looking into hoomd-blue and this is a widely used simulation suite I would like to include support for hoomd-blue in AMEP.
They already got a python library so the only thing we have to do is translate to AMEP.

**Comment by kai-luca** [comment]
https://github.com/glotzerlab/gsd
Here is their library for Data IO in Python.

**Comment by kay-ro** [comment]
connected to #47
