### ISSUE TITLE
BUG: Change of timestep does not lead to a change of the physical time

### ISSUE THREAD

**Issue by descho00** [amepproject/amep#6]
### Description:

A new timestep set by `traj.dt = <timestep>` does not affect `traj.times`.

### Code for reproduction:

```python
import amep
traj = amep.load.traj(<path-to-traj>)
traj.dt = <timestep>
print(traj.times)
```

### Python and AMEP versions:

AMEP: 1.0.0
Python: 3.12.2

### How did you install AMEP?

conda

**Comment by hechtprojects** [comment]
@descho00 Thank you for reporting this bug! The fix will be part of patch release v1.0.1.
